# Generated by Django 4.0.2 on 2022-03-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
