# Generated by Django 4.0.2 on 2022-03-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsite', '0002_student_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsite.semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsite.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentsite.semester'),
        ),
    ]
