# Generated by Django 4.0.2 on 2022-03-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsite', '0003_score_semester_semester_student_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ManyToManyField(related_name='subjects', to='studentsite.Subject'),
        ),
    ]
