# Generated by Django 4.0.2 on 2022-03-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsite', '0006_remove_score_subject_score_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsite.semester'),
        ),
        migrations.AddField(
            model_name='cocurriculum',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsite.semester'),
        ),
        migrations.AddField(
            model_name='remark',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsite.semester'),
        ),
        migrations.AlterField(
            model_name='cocurriculum',
            name='dancing',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cocurriculum',
            name='drawing',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cocurriculum',
            name='essays',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cocurriculum',
            name='presents',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cocurriculum',
            name='singing',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cocurriculum',
            name='sports',
            field=models.CharField(blank=True, choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Race', 'Race'), ('Kabaddi', 'Kabaddi'), ('Tennis', 'Tennis')], max_length=64),
        ),
    ]
