# Generated by Django 4.0.2 on 2022-03-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsite', '0007_achievement_semester_cocurriculum_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='student',
        ),
        migrations.AddField(
            model_name='semester',
            name='student',
            field=models.ManyToManyField(to='studentsite.Student'),
        ),
    ]
