# Generated by Django 4.0.2 on 2022-03-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsite', '0010_remove_subject_semester_subject_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ManyToManyField(to='studentsite.Semester'),
        ),
    ]
