# Generated by Django 4.0.2 on 2022-03-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsite', '0012_remove_subject_semester_remove_subject_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='physics',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject_assignment_marks',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject_exam_marks',
        ),
        migrations.AddField(
            model_name='score',
            name='biology_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='biology_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='chemistry_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='chemistry_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='computer_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='computer_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='english_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='english_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='geography_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='geography_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='hindi_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='hindi_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='history_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='history_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='mathematics_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='mathematics_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='physics_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='physics_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='sanskrit_assingment_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='sanskrit_exam_marks',
            field=models.FloatField(default=0, max_length=64, null=True),
        ),
    ]
